[package]
name = "userspace-tests"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_memory_lifecycle"
test = false

[dependencies]
gaxera-abi = { path = "../gaxera-abi" }
libgaxera = { path = "../libgaxera", features = ["alloc_error_handler"] }

[features]
test-memory-lifecycle = []

[lints]
workspace = true
