[package]
name = "test_ring3_heap"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_ring3_heap"
test = false

[dependencies]
kernel-core = { path = "../kernel-core" }
gaxera-abi = { path = "../gaxera-abi" }
libgaxera = { path = "../libgaxera", features = ["alloc_error_handler"] }

[lints]
workspace = true

[features]
test-ring3-heap = []
